language: scala
sudo: true

jdk:
  - oraclejdk7
  - oraclejdk8
  - openjdk7

install:
    - ( test -d "$SPARK_HOME" && test "$(ls -A "$SPARK_HOME")" ) || ( wget -O spark.tgz "http://d3kbcqa49mib13.cloudfront.net/spark-2.1.0-bin-hadoop2.6.tgz" && mkdir -p "$SPARK_HOME" && tar xvf "spark.tgz" -C "$SPARK_HOME" --strip-components 1 )

env:
  global:    
    - SPARK_HOME="$HOME/spark21/"
  matrix:
    - SCALA_BASE_VERSION="2.11"
    - SCALA_BASE_VERSION="2.10"

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
    directories:
        - $HOME/.m2
        - $HOME/.gradle/caches/
        - $HOME/.gradle/wrapper/
        - $SPARK_HOME

script: ./gradlew clean build -x integTest -x :sparkling-water-py:build -PsparklingTestEnv=local -PsparkHome=$SPARK_HOME -PscalaBaseVersion=$SCALA_BASE_VERSION

# To solve BufferOverflow on OpenJDK7 we setup short hostname (<64characters)
# See:
#   - ISSUE-5227: https://github.com/travis-ci/travis-ci/issues/5227
#   - https://docs.travis-ci.com/user/hostname
#   - https://github.com/mockito/mockito/blob/master/.travis.yml
addons:
    hosts:
        - sw-test-host
    hostname: sw-test-host

