language: scala
sudo: true

jdk:
  - oraclejdk7
  - oraclejdk8
  - openjdk7

scala:
  - 2.10.6

install:
    - ( test -d "$SPARK_HOME" && test "$(ls -A "$SPARK_HOME")" ) || ( wget -O spark.tgz "http://mirrors.ocf.berkeley.edu/apache/spark/spark-2.0.0-preview/spark-2.0.0-preview-bin-hadoop2.4.tgz" && mkdir -p "$SPARK_HOME" && tar xvf "spark.tgz" -C "$SPARK_HOME" --strip-components 1 )

env:
  - SPARK_HOME="$HOME/spark20/"

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
    directories:
        - $HOME/.m2
        - $HOME/.gradle/caches/
        - $HOME/.gradle/wrapper/
        - $SPARK_HOME

script: ./gradlew clean build -x integTest -x :sparkling-water-py:build -PsparklingTestEnv=local -PsparkHome=$SPARK_HOME

# To solve BufferOverflow on OpenJDK7 we setup short hostname (<64characters)
# See:
#   - ISSUE-5227: https://github.com/travis-ci/travis-ci/issues/5227
#   - https://docs.travis-ci.com/user/hostname
#   - https://github.com/mockito/mockito/blob/master/.travis.yml
addons:
    hosts:
        - sw-test-host
    hostname: sw-test-host

