language: scala
sudo: true

jdk:
  - oraclejdk7
  - oraclejdk8
  - openjdk7

scala:
  - 2.10.6

install:
  - ( test -d "$SPARK_HOME" && test "$(ls -A "$SPARK_HOME")" ) || ( wget -O spark.tgz "http://mirrors.ocf.berkeley.edu/apache/spark/spark-1.5.2/spark-1.5.2-bin-cdh4.tgz" && mkdir -p "$SPARK_HOME" && tar xvf "spark.tgz" -C "$SPARK_HOME" --strip-components 1 )

env:
  - SPARK_HOME="$HOME/spark/"

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
    directories:
        - $HOME/.m2
        - $HOME/.gradle/caches/
        - $HOME/.gradle/wrapper/
        - $SPARK_HOME

script: ./gradlew clean build -x integTest -x :sparkling-water-py:build -PsparklingTestEnv=local -PsparkHome=$SPARK_HOME

# To solve BufferOverflow on OpenJDK7: see https://github.com/travis-ci/travis-ci/issues/5227
before_install:
  - cat /etc/hosts # optionally check the content *before*
  - sudo hostname "$(hostname | cut -c1-63)"
  - sed -e "s/^\\(127\\.0\\.0\\.1.*\\)/\\1 $(hostname | cut -c1-63)/" /etc/hosts | sudo tee /etc/hosts
  - cat /etc/hosts # optionally check the content *after*
